apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello-world
  template:
    metadata:
      labels:
        app: go-web-hello-world
    spec:
      containers:
      - image: lemonmxy1/go-web-hello-world:v0.1
        imagePullPolicy: Always
        name: go-web-hello-world
        ports:
        - containerPort: 8081
          name: http-port
          protocol: TCP


apiVersion: v1
kind: Service
metadata:
  name: go-web
spec:
  ports:
  - name: http
    nodePort: 31080
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-web-hello-world
  type: NodePort
